---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zts-claim1
  namespace: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zts-sc 
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    type: database
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.3
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
          - name: existingvolumename
            mountPath: "/mnt/data"
      volumes:
      - name: existingvolumename
        persistentVolumeClaim:
          claimName: zts-claim1
