---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zts-claim2
  namespace: mariadb2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb2
  labels:
    app: mariadb2
    type: database
spec:
  selector:
    matchLabels:
      app: mariadb2
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb2
        type: database
    spec:
      containers:
        - name: mariadb2
          image: quay.io/bitnami/mariadb:10.3
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
          - name: existingvolumename
            mountPath: "/mnt/data"
          - name: existingvolumename3
            mountPath: "/mnt/data3"
      volumes:
      - name: existingvolumename
        persistentVolumeClaim:
          claimName: zts-claim2
      - name: existingvolumename3
        persistentVolumeClaim:
          claimName: zts-claim3
